nailsproject/nails/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='home'),
    path('masters/', show_masters, name='masters'),
    path('services/', show_services, name='services'),
    path('registration/', RegistrationCreateView.as_view(), name='reg'),
    path('master/<slug:master_slug>/', show_master, name='master'),
    path('registration/<int:pk>', ShowRegistration.as_view(), name='confirmation')
]

nailsproject/nailsproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from nailsproject import settings
 
urlpatterns = [
    path('', include('nails.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nailsproject/nails/models.py
from distutils.command.upload import upload
from django.db import models
from django.urls import reverse

class MainPage(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок главной страницы')
    description_upper = models.TextField(blank=True, verbose_name='Описание главной страницы над фотографиями')
    picture1 = models.ImageField(blank=True, upload_to="photos/%Y/%m/%d/", verbose_name='Фотография на странице')
    picture2 = models.ImageField(blank=True, upload_to="photos/%Y/%m/%d/", verbose_name='Фотография на странице')
    picture3 = models.ImageField(blank=True, upload_to="photos/%Y/%m/%d/", verbose_name='Фотография на странице')
    description_under = models.TextField(blank=True, verbose_name='Описание главной страницы под фотографиями')
    
    def __str__(self):
        return f'{self.title}'
    
    class Meta:
        verbose_name = 'Главная страница'
        verbose_name_plural = 'Главные страницы'
        
# Create your models here.
class Master(models.Model):
    name = models.CharField(max_length=100, verbose_name='Имя мастера')
    slug = models.SlugField(max_length=100, unique=True, db_index=True, verbose_name='URL')
    photo = models.ImageField(upload_to="photos/%Y/%m/%d/", verbose_name='Фото мастера')
    grade = models.CharField(max_length=50, verbose_name='Занимаемая должность', null=True)
    experience = models.CharField(max_length=50, verbose_name='Стаж', null=True)
    rating = models.IntegerField(default=1, verbose_name='Рейтинг мастера') #нужно придумать что делать с рейтингом!
    description = models.TextField(max_length=500, verbose_name='О мастере')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('master', kwargs={'master_slug': self.slug})

    class Meta:
        verbose_name = 'Мастер'
        verbose_name_plural = 'Мастера'

class Service(models.Model):
    title = models.CharField(max_length=50, db_index=True, verbose_name='Наименование услуги')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('service', kwargs={'service_id': self.pk})

    class Meta:
        verbose_name = 'Услуга'
        verbose_name_plural = 'Услуги'

class MasterService(models.Model):
    master = models.ForeignKey(Master, on_delete=models.PROTECT, verbose_name='Мастер')
    services = models.ForeignKey(Service, on_delete=models.PROTECT, verbose_name='Услуга')
    duration = models.IntegerField(verbose_name='Продолжительность в минутах')
    price = models.IntegerField(verbose_name='Цена')
        #ManyToManyField или ForeignKey!!!
    def __str__(self):
        return f'{self.master} {self.services}' 

    class Meta:
        verbose_name = 'Продолжительность и цена услуги'
        verbose_name_plural = 'Продолжительность и цена услуги'

class Registration(models.Model):
    master = models.ForeignKey(Master, on_delete=models.PROTECT, verbose_name='Мастер')
    service = models.ManyToManyField(Service, verbose_name='Услуга')
    masterservice = models.ManyToManyField(MasterService)
    phone_number = models.CharField(max_length=11, verbose_name='Номер телефона')
    users_name = models.CharField(max_length=100, verbose_name='ФИО')
    reg_date = models.DateField(null=True, verbose_name='Дата записи')
    reg_time = models.TimeField(null=True, verbose_name='Время записи')

    def get_absolute_url(self):
        return reverse('confirmation', kwargs={'pk': self.pk})

    def __str__(self):
        return f'{self.users_name}'

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Запись'

nailsproject/nails/forms.py
from django import forms
from django.forms import ModelForm, MultipleChoiceField, SelectMultiple
from .models import *

class DateInput(forms.DateInput):
    input_type = 'date'

class TimeInput(forms.TimeInput):
    input_type = 'time'

class AddRegistrationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['master'].empty_label = "Мастер не выбран"

    class Meta:
        model = Registration
        fields = ['master', 'service', 'reg_date', 'reg_time', 'users_name', 'phone_number']
        service = MasterService.objects.all()
        widgets = {
            'reg_date': DateInput(),
            'reg_time': TimeInput(),
            'service': forms.CheckboxSelectMultiple
        }

nailsproject/nails/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView
from nails.forms import AddRegistrationForm
from . models import *

def index(request):
    main_page = MainPage.objects.all()
    context = {
        'main_page': main_page,
        'title': 'Главная страница',
        'nbar': 'home'
    }
    return render(request, 'nails/index.html', context=context)
# Create your views here.

def show_masters(request): # Отображение страницы с выбором мастеров
    master = Master.objects.all()
    context = {
        'master': master,
        'title': 'Выбор мастера',
        'nbar': 'masters'
    }
    return render(request, 'nails/masters.html', context=context)


def show_master(request, master_slug):  # Отображение страницы мастера
    
    master = get_object_or_404(Master, slug=master_slug)
    service = Service.objects.all()
    master_service = MasterService.objects.filter(master__slug=master_slug).order_by('services__id', 'services')
    
    context = {
        'master_service': master_service,
        'master': master,
        'service': service,
        'title': 'Подробнее о мастере',
        'duration': ' минут',
        'price': ' руб',
        'part': ' / ноготь',
        'nbar': 'masters',
    }
    return render(request, 'nails/master.html', context=context)


def show_services(request):

    context = {
        'nbar': 'services'
    }

    return render(request, 'nails/services.html', context=context)

# def show_reg(request):
#     form = AddRegistrationForm()
#     return render(request, 'nails/registration.html', {'form': form, 'title': 'Запись', 'nbar': 'reg',})

class RegistrationCreateView(CreateView): # создание формы-регистрации
    form_class = AddRegistrationForm
    template_name = 'nails/registration.html'
    #success_url = reverse_lazy('confirmation')
    
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Запись'
        context['nbar'] = 'reg'
        return context


class ShowRegistration(DetailView): # вывод информации после регистрации
    model = Registration
    template_name = 'nails/confirmation.html'
    context_object_name = 'confirmation' 


    #servs = Service.objects.filter(reg__id=Registration.pk) 

    # https://djbook.ru/rel1.9/topics/db/queries.html#lookups-that-span-relationships

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Подтверждение записи"
        context['nbar'] = "reg"
        context['master'] = "Запись к мастеру: "
        context['service'] = "Запись на услуги: "
        context['duration'] = "Продолжительность сеанса: "
        context['price'] = "Стоимость услуг: "
        context['reg_serv'] = Service.objects.filter(registration__id=self.object.id)
        context['masterservice'] = MasterService.objects.filter(registration__id=self.object.id)
        return context

# def confirmation(request):
#     return render(request, 'nails/confirmation.html', context= {'title': 'Подтверждение записи', 'nbar': 'reg'})


    
# def show_reg(request):
#     master = Master.objects.all()
#     service = Service.objects.all()
#     context = {
#         'master': master,
#         'service': service,
#         'nbar': 'reg',
#     }
#     return render(request, 'nails/registration.html', context=context)

nailsproject/templates/nails/base.html
<!DOCTYPE html>
<head>
    <title>{{title}}</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <!-- Nav bar -->
    <ul class="nav nav-pills nav-fill">
        <li class="nav-item">
          <a class="nav-link {% if nbar == 'home' %}active{% endif %}" href="{% url 'home' %}">Главная</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if nbar == 'masters' %}active{% endif %}" href="{% url 'masters' %}">Выбор мастера</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if nbar == 'services' %}active{% endif %}" href="{% url 'services' %}">Услуги</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if nbar == 'reg' %}active{% endif %}" href="{% url 'reg' %}">Запись</a>
        </li>
      </ul>

      


{% block content %}
{% endblock %}
</body>
</html>

nailsproject/templates/nails/confirmation.html
{% extends 'nails/base.html' %}
{% block content %}
<div class="container ms-4 mt-4">
<h5 class="ms-3">{{confirmation}}, Вы успешно записались!</h5><br>
<h><b>{{master}}</b>{{confirmation.master}}</p>
<p><b>{{service}}</b>
    {% for rs in reg_serv %}
    <ul>
        <li>{{rs}}</li>
    </ul>
    {% endfor %}
</p>
<p><b>{{duration}}</b>
    {% for ms in masterservice %}
    <ul>
        <li>{{ms.duration}}</li>
    </ul>
    {% endfor %}
</p>
<p><b>{{price}}</b>
    {% for ms in masterservice %}
    <ul>
        <li>{{ms.price}}</li>
    </ul>
    {% endfor %}
</p>
<a class="btn btn-outline-primary mt-4 me-4 px-4 py-2" href="{% url 'home' %}" role="button">ОК</a>
</div>
{% endblock %}

nailsproject/templates/nails/index.html
{% extends 'nails/base.html' %}
{% block content %}
    {% for m in main_page %}
        <div class="mx-auto mt-2 mb-4" style="width: 200px;">
          <h3>{{m.title}}</h3>
        </div>
        <div class="ms-4 my-4"> <!-- Текст над фото -->
          <p>{{m.description_upper|linebreaksbr}}</p>
        </div>
        <div class="mx-auto mb-4" style="width: 200px;">
          <h4>Примеры ниш</h4>
        </div>
            <div class="container mb-3"> <!-- Контейнер с изображениями -->
                <div class="row">
                    <div class="col-sm">
                      <img src="{{m.picture1.url}}" class="img-fluid img-thumbnail rounded" width="300px" height="300px" alt="Автосервис">
                    </div>
                    <div class="col-sm">
                      <img src="{{m.picture2.url}}" class="img-fluid img-thumbnail rounded" width="300px" height="300px" alt="Массажный салон">
                    </div>
                    <div class="col-sm">
                      <img src="{{m.picture3.url}}" class="img-fluid img-thumbnail rounded" width="300px" height="300px" alt="Стоматология">
                    </div>
                </div>
            </div>
            <div class="container my-4"> <!-- Контейнер с кнопками -->
              <h6>Вы можете познакомиться с:</h6>
              <a class="btn btn-primary my-2 me-4" href="{% url 'masters' %}" role="button">Выбор мастера</a>
              <a class="btn btn-primary my-2 me-4" href="{% url 'services' %}" role="button">Услуги</a>
              <a class="btn btn-primary my-2" href="{% url 'reg' %}" role="button">Запись</a>
            </div>
        <div class="ms-4"> <!-- Текст под фото -->
          <p>{{m.description_under|linebreaksbr}}</p>
        </div>
    {% endfor %}
{% endblock %}

nailsproject/templates/nails/master.html
{% extends 'nails/base.html' %}
{% load nails_tags %}
{% block content %}
<div class="container mt-4 mb-4 mb-4">
    <img src="{{master.photo.url}}" class="img-fluid img-thumbnail rounded mb-3 me-4 float-start" width="140px" height="150px" alt="{{m.name}}">
    <h4>{{master.name}}</h4>
    <p>{{master.grade}}
       {{master.experience}}</p>
    <p>Рейтинг: {{master.rating}}</p>
    <p>{{master.description}}</p></br>
</div>
<div style="clear:both"></div>
<h4 class="ms-4"><a href="{% url 'services' %}">Услуги</a></h4> <!-- Сделать надпись обтекаемой под фотку -->
<div class="container mt-5 mb-4"> <!-- ПЕРЕДЕЛАТЬ КОНТЕЙНЕР ПОД ГОРИЗОНТАЛЬНУЮ ТАБЛИЦУ С УЧЁТОМ PeopleService -->
    <div class="row">
        <div class="col-sm">
            <h6>Наименование</h6>  
            <ul>
                {% for mas in master_service %}
                <li>{{mas}}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-sm">
            <h6>Продолжительность</h6>
                <ul>
                    {% for mas in master_service %}
                        {% if mas.services.title == 'Дизайн' or mas.services.title == 'Наращивание' %}
                            <li>{{mas.duration}}{{duration}}{{part}}</li>
                        {% else %}
                            <li>{{mas.duration}}{{duration}}</li>
                        {% endif %}
                    {% endfor %}
                </ul>    
        </div>
        <div class="col-sm">
            <h6>Цена</h6>
                <ul>
                    {% for mas in master_service %}
                        {% if mas.services.title == 'Дизайн' or mas.services.title == 'Наращивание' %}
                            <li>{{mas.price}}{{price}}{{part}}</li>
                        {% else %}
                            <li>{{mas.price}}{{price}}</li>
                        {% endif %}
                    {% endfor %}
                </ul>
        </div>
    </div>
    <a class="btn btn-outline-primary mb-4 me-4 mt-3" href="{% url 'reg' %}" role="button">Записаться</a>
</div>
    <h5 class="ms-4">Отзывы(кол-во):</h5>

{% endblock %}

nailsproject/templates/nails/masters.html
{% extends 'nails/base.html' %}
{% block content %}
<div class="mx-auto mt-2" style="width: 200px;">
    <h3>Мастера</h3>
</div>
<div class="container mt-5 mb-4">
    {% for m in master %}
      <img src="{{m.photo.url}}" class="img-fluid img-thumbnail rounded mb-3 me-4 float-start" width="125px" height="100px" alt="{{m.name}}">
      <h4><a href="{{ m.get_absolute_url }}">{{m.name}}</a></h4>
      <p>{{m.grade}}
      {{m.experience}}</p>
      <p>{{m.rating}}</p>
          <a class="btn btn-outline-primary mb-4 me-4" href="{{ m.get_absolute_url }}" role="button">Подробнее о мастере</a>
          <a class="btn btn-outline-primary mb-4 me-4" href="{% url 'reg' %}" role="button">Записаться</a>
          <a class="btn btn-outline-primary mb-4" href="#" role="button">Отзывы</a></br></br></br>
    {% endfor %}
</div>
{% endblock %}

nailsproject/templates/nails/registration.html
{% extends 'nails/base.html' %}
{% block content %}
<div class="mx-auto mt-2" style="width: 200px;">
    <h3>Запись</h3>
</div>
<div class="container ms-4 mt-4">
  <form action="{% url 'reg' %}" method="post">
    {% csrf_token %}
    <div class="row">
      {{ form.non_field_errors }}
      <div class="col-md-4">
        <div class="fieldWrapper">
          {{ form.master.errors }}
          <label for="id_master">Выбор мастера:</label>
          {{ form.master }} </br> </br>
        </div>
        <div class="fieldWrapper">
          {{ form.service.errors }}
          <label for="id_service">Выбор услуг:</label>
          {{ form.service }}
        </div>
      </div>
      <div class="col-md">
        <div class="fieldWrapper">
          {{ form.reg_date.errors }}
          <label for="id_reg_date">Выбор даты:</label>
          {{ form.reg_date }} </br> </br>
        </div>
        <div class="fieldWrapper">
          {{ form.reg_time.errors }}
          <label for="id_reg_time">Выбор времени:</label>
          {{ form.reg_time }}
        </div>
      </div>
      <div class="col-sm">
        <div class="fieldWrapper">
          {{ form.users_name.errors }}
          <label for="id_users_name">Ваше имя:</label>
          {{ form.users_name }} <br> <br>
        </div>
        <div class="fieldWrapper">
          {{ form.phone_number.errors }}
          <label for="id_phone_number">Ваш номер телефона:</label>
          {{ form.phone_number }}
        </div>
      </div>
    </div>
    <div class='d-flex justify-content-end'>
      <button class="btn btn-primary pull-right" type="submit">Добавить</button>
    </div>
  </form>
</div>
{% endblock %}

nailsproject/templates/nails/services.html
{% extends 'nails/base.html' %}
{% load nails_tags %}
{% block content %}
<div class="mx-auto mt-2" style="width: 200px;">
    <h3>Услуги</h3>
</div>
<div class="ms-4 mt-4">
    <ul>
    {% servs as services %}
        {% for s in services %}
            <li>{{s.title}}</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}